# Generated by Django 5.0.6 on 2024-07-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='org_id',
            new_name='orgId',
        ),
    ]
