# Generated by Django 5.0.6 on 2024-07-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_org_id_organization_orgid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userId',
        ),
    ]
